apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 3scale
  name: 'service-c'
  annotations: {}
  labels:
    app: service-c

    app.kubernetes.io/component: service-c
    app.kubernetes.io/instance: service-c
    app.kubernetes.io/name: service-c
    app.kubernetes.io/part-of: service-c
    app.openshift.io/runtime-namespace: 3scale
spec:
  selector:
    matchLabels:
      app: service-c
  replicas: 2
  template:
    metadata:
      labels:
        app: service-c
        version: v1
        app.kubernetes.io/component: service-c
        app.kubernetes.io/name: service-c
        deployment: service-c
    spec:
      containers:
        - name: container
          image: >-
            quay.io/appdev_playground/3scale-demo:service-c-0.0.1
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
